theme: jekyll-theme-slate
title: Cognitive Robotics TUT
description: This page contains material related to the research about Human-Robot interaction performed in the Cognitive Robotics group of Tampere University of Technology.
